EEEEEEE
======================================================================
ERROR: test_server_run__exec_with_args (__main__.TestServer)
Send the server "run" with arguments. Output must reflect arguments.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "server_run_kill_test.py", line 75, in test_server_run__exec_with_args
    with ongoing_process([os.path.join('.', 'jobserver')]) as p:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/furkan/csc209-w19/grading/mark_a4/marking_scripts/test_helpers.py", line 530, in ongoing_process
    shell=shell
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './jobserver': './jobserver'

======================================================================
ERROR: test_server_run__exec_with_no_args (__main__.TestServer)
Send the server "run" with no arguments. Confirmation should be sent.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "server_run_kill_test.py", line 28, in test_server_run__exec_with_no_args
    with ongoing_process([os.path.join('.', 'jobserver')]) as p:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/furkan/csc209-w19/grading/mark_a4/marking_scripts/test_helpers.py", line 530, in ongoing_process
    shell=shell
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './jobserver': './jobserver'

======================================================================
ERROR: test_server_run__invalid_exec (__main__.TestServer)
Send the server "run" with invalid executable. Command should fail. (exec error.)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "server_run_kill_test.py", line 19, in test_server_run__invalid_exec
    with ongoing_process([os.path.join('.', 'jobserver')]) as p:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/furkan/csc209-w19/grading/mark_a4/marking_scripts/test_helpers.py", line 530, in ongoing_process
    shell=shell
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './jobserver': './jobserver'

======================================================================
ERROR: test_server_run__job_termination_announced (__main__.TestServer)
Verify that job close is appropriately announced.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "server_run_kill_test.py", line 67, in test_server_run__job_termination_announced
    with ongoing_process([os.path.join('.', 'jobserver')]) as p:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/furkan/csc209-w19/grading/mark_a4/marking_scripts/test_helpers.py", line 530, in ongoing_process
    shell=shell
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './jobserver': './jobserver'

======================================================================
ERROR: test_server_run__stderr_sent_to_client (__main__.TestServer)
Send the server "run", verify that output is sent to client.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "server_run_kill_test.py", line 58, in test_server_run__stderr_sent_to_client
    with ongoing_process([os.path.join('.', 'jobserver')]) as p:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/furkan/csc209-w19/grading/mark_a4/marking_scripts/test_helpers.py", line 530, in ongoing_process
    shell=shell
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './jobserver': './jobserver'

======================================================================
ERROR: test_server_run__stdout_only_sent_to_watching_client (__main__.TestServer)
Run a job. Connect second client. Second client should get no messages.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "server_run_kill_test.py", line 49, in test_server_run__stdout_only_sent_to_watching_client
    with ongoing_process([os.path.join('.', 'jobserver')]) as p:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/furkan/csc209-w19/grading/mark_a4/marking_scripts/test_helpers.py", line 530, in ongoing_process
    shell=shell
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './jobserver': './jobserver'

======================================================================
ERROR: test_server_run__stdout_sent_to_client (__main__.TestServer)
Send the server "run", verify that output is sent to client.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "server_run_kill_test.py", line 41, in test_server_run__stdout_sent_to_client
    with ongoing_process([os.path.join('.', 'jobserver')]) as p:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/furkan/csc209-w19/grading/mark_a4/marking_scripts/test_helpers.py", line 530, in ongoing_process
    shell=shell
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './jobserver': './jobserver'

----------------------------------------------------------------------
Ran 7 tests in 7.052s

FAILED (errors=7)
