.EEEE.F.F..........
======================================================================
ERROR: test_treegen_in_tests_child_PID_not_found (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/furkan/csc209-w19/grading/mark_a2/marking_scripts/test_helpers.py", line 161, in _t
    stdout, stderr, returncode = self._run_exec(args=args, input_=input_, timeout=timeout, check=check)
  File "/home/furkan/csc209-w19/grading/mark_a2/marking_scripts/test_helpers.py", line 101, in _run_exec
    **kwargs)
  File "/home/furkan/csc209-w19/grading/mark_a2/marking_scripts/test_helpers.py", line 503, in _exec
    raise e from e
  File "/home/furkan/csc209-w19/grading/mark_a2/marking_scripts/test_helpers.py", line 499, in _exec
    stdout, stderr = proc.communicate(timeout=timeout, input=input_)
  File "/usr/lib/python3.6/subprocess.py", line 843, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1515, in _communicate
    self._check_timeout(endtime, orig_timeout)
  File "/usr/lib/python3.6/subprocess.py", line 871, in _check_timeout
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['./compare_tree', '31000']' timed out after 2 seconds

======================================================================
ERROR: test_treegen_in_tests_child_PID_not_found_build_continues (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/furkan/csc209-w19/grading/mark_a2/marking_scripts/test_helpers.py", line 161, in _t
    stdout, stderr, returncode = self._run_exec(args=args, input_=input_, timeout=timeout, check=check)
  File "/home/furkan/csc209-w19/grading/mark_a2/marking_scripts/test_helpers.py", line 101, in _run_exec
    **kwargs)
  File "/home/furkan/csc209-w19/grading/mark_a2/marking_scripts/test_helpers.py", line 503, in _exec
    raise e from e
  File "/home/furkan/csc209-w19/grading/mark_a2/marking_scripts/test_helpers.py", line 499, in _exec
    stdout, stderr = proc.communicate(timeout=timeout, input=input_)
  File "/usr/lib/python3.6/subprocess.py", line 843, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1515, in _communicate
    self._check_timeout(endtime, orig_timeout)
  File "/usr/lib/python3.6/subprocess.py", line 871, in _check_timeout
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['./compare_tree', '31003']' timed out after 2 seconds

======================================================================
ERROR: test_treegen_in_tests_child_exe_not_found (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/furkan/csc209-w19/grading/mark_a2/marking_scripts/test_helpers.py", line 161, in _t
    stdout, stderr, returncode = self._run_exec(args=args, input_=input_, timeout=timeout, check=check)
  File "/home/furkan/csc209-w19/grading/mark_a2/marking_scripts/test_helpers.py", line 101, in _run_exec
    **kwargs)
  File "/home/furkan/csc209-w19/grading/mark_a2/marking_scripts/test_helpers.py", line 503, in _exec
    raise e from e
  File "/home/furkan/csc209-w19/grading/mark_a2/marking_scripts/test_helpers.py", line 499, in _exec
    stdout, stderr = proc.communicate(timeout=timeout, input=input_)
  File "/usr/lib/python3.6/subprocess.py", line 843, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1515, in _communicate
    self._check_timeout(endtime, orig_timeout)
  File "/usr/lib/python3.6/subprocess.py", line 871, in _check_timeout
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['./compare_tree', '31001']' timed out after 2 seconds

======================================================================
ERROR: test_treegen_in_tests_child_exe_not_found_build_continues (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/furkan/csc209-w19/grading/mark_a2/marking_scripts/test_helpers.py", line 161, in _t
    stdout, stderr, returncode = self._run_exec(args=args, input_=input_, timeout=timeout, check=check)
  File "/home/furkan/csc209-w19/grading/mark_a2/marking_scripts/test_helpers.py", line 101, in _run_exec
    **kwargs)
  File "/home/furkan/csc209-w19/grading/mark_a2/marking_scripts/test_helpers.py", line 503, in _exec
    raise e from e
  File "/home/furkan/csc209-w19/grading/mark_a2/marking_scripts/test_helpers.py", line 499, in _exec
    stdout, stderr = proc.communicate(timeout=timeout, input=input_)
  File "/usr/lib/python3.6/subprocess.py", line 843, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.6/subprocess.py", line 1515, in _communicate
    self._check_timeout(endtime, orig_timeout)
  File "/usr/lib/python3.6/subprocess.py", line 871, in _check_timeout
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['./compare_tree', '31004']' timed out after 2 seconds

======================================================================
FAIL: test_treegen_in_tests_cmdline_args (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/furkan/csc209-w19/grading/mark_a2/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: 'Encountered incorrect process name when traversing through tree.\n' != '1'
- Encountered incorrect process name when traversing through tree.
+ 1

======================================================================
FAIL: test_treegen_in_tests_cmdline_not_exist (__main__.TestTreeGeneration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/furkan/csc209-w19/grading/mark_a2/marking_scripts/test_helpers.py", line 190, in _t
    self.assertEqual(stdout, expected_stdout)
AssertionError: 'Encountered a non-NULL next_siblin[216 chars]t.\n' != '1'
- Encountered a non-NULL next_sibling or child_procs pointer which was supposed to be NULL (the next_sibling pointer of the last sibling, or the child_procs pointer of a process with no children, should be NULL); Possible reason: Extra TreeNodes present.
+ 1

----------------------------------------------------------------------
Ran 19 tests in 8.121s

FAILED (failures=2, errors=4)
